### PR TITLE
Update to ember@2.15 and load FileSaver from npm instead of bower.

### PR DESCRIPTION
**Pull request by GCheung55**
Fix for #3.

### CODE REVIEW

**Comment by GCheung55** [comment]
@panthony I've tried running `npm test`, which runs `ember try:each` but it seems to fail with an error I don't understand: https://gist.github.com/GCheung55/dd3275f50d79b5cf5f18a8fcf47bc97c

Running `ember test` is just fine. Seems to fail to run with ember@2.8. Can you give this a shot? Maybe it's just my machine.

**Comment by GCheung55** [comment]
I found the problem. I cloned the repo into a directory that has a name with spaces and parens. Ref: https://github.com/TryGhost/Ghost/issues/3206#issuecomment-51593121

Moving the directory somewhere else is working for me now.

**Comment by jrr** [comment]
@panthony can this be merged/released? I'm currently referencing a copy of GCheung55's branch in my project, and I'd like to switch back to upstream.

**Comment by panthony** [comment]
@GCheung55 @jrr I published a new version (`1.0.0`) with this PR, thanks for the contribution and sorry for the unresponsiveness I got back from holidays yesterday I have a lot on my plate :)

**Pull request merged**
