### PR TITLE
Fix file-saver to be available as dependencies

### PR DESCRIPTION
**Pull request by GreatWizard**
Currently file-saver dependency is not download through npm.
It needs to be in the "dependencies" attribute.

 🥂 Cheers

### CODE REVIEW

**Comment by panthony** [comment]
Hi @GreatWizard ,

Did you use `ember install ember-cli-file-saver`?

Using `ember install` it should execute the [blueprint](https://github.com/cogniteev/ember-cli-file-saver/blob/master/blueprints/ember-cli-file-saver/index.js#L9) and add `file-saver` as NPM package:

```bash
 % ember install ember-cli-file-saver
NPM: Installed ember-cli-file-saver
installing ember-cli-file-saver
  install package file-saver
NPM: Installed file-saver@^1.3.3
Installed addon package.
```

If the addon was installed using `NPM` you should be able to retrieve the `file-saver` dependency by executing the blueprint manually:

```bash
ember generate ember-cli-file-saver
```

**Comment by GreatWizard** [comment]
Oh you right, I didn't see it.
Thanks for the info.

Do you agree if we put file-saver in the dependencies of the package.json instead of having blueprints?

Blueprints can be missed or not updated (in the application of users) if you upgrade the dependencies in the addon and they don't reinstall it with ember-cli.

I will update the PR

**Comment by panthony** [comment]
@GreatWizard Sorry for the delay, I do agree it could be simpler overall. If you do not mind rebasing on the new master I'll merge the PR.

Thanks !

**Comment by GreatWizard** [comment]
I just update it ;)

**Comment by panthony** [comment]
@GreatWizard Published as `1.2.0`, thanks again

**Pull request merged**
